import logging
from typing import Any

from zigzag.cost_model.cost_model import CostModelEvaluation
from zigzag.datatypes import Constants, MemoryOperand
from zigzag.mapping.temporal_mapping import TemporalMappingType
from zigzag.stages.stage import Stage as ZigZagStage

from stream.cost_model.tile_aware_latency import TileAwareLatencyEstimator
from stream.hardware.architecture.accelerator import Accelerator
from stream.hardware.architecture.core import Core
from stream.mapping.mapping import Mapping
from stream.stages.context import StageContext
from stream.stages.stage import Stage, StageCallable
from stream.workload.workload import ComputationNode, Workload

logger = logging.getLogger(__name__)


class CoreCostEstimationStage(Stage):
    """
    Stage that creates a TileAwareLatencyEstimator and sets it on the context.

    This replaces the old CoreCostLUT-based approach (D-04, D-05): instead of running
    ZigZag/AIE estimators and storing results in a LUT, we create a lightweight
    TileAwareLatencyEstimator that computes latency on demand from node dimensions
    and kernel utilization.
    """

    REQUIRED_FIELDS = (
        "workload",
        "accelerator",
        "mapping",
        "loma_lpf_limit",
        "output_path",
        "temporal_mapping_type",
    )

    def __init__(
        self,
        list_of_callables: list[StageCallable],
        ctx: StageContext,
    ):
        """
        Initialize the stage.
        """
        super().__init__(list_of_callables, ctx)
        self.workload: Workload = self.ctx.get("workload")
        self.accelerator: Accelerator = self.ctx.get("accelerator")
        self.mapping: Mapping = self.ctx.get("mapping")

        self.valid_allocations: dict[ComputationNode, list[Core]] = {}
        for node in self.workload.get_computation_nodes():
            node_mapping = self.mapping.get(node)
            if node_mapping is None:
                raise ValueError(f"No mapping found for node {node.name}")
            assert len(node_mapping.resource_allocation) == 1, (
                "TODO: Support multiple resource allocation entries per node"
            )
            cores = node_mapping.resource_allocation[0]
            self.valid_allocations[node] = cores

    def run(self):
        logger.info("Start CoreCostEstimationStage.")
        latency_estimator = TileAwareLatencyEstimator(self.workload, self.mapping)
        logger.info("Finished CoreCostEstimationStage.")

        self.ctx.set(
            workload=self.workload,
            accelerator=self.accelerator,
            latency_estimator=latency_estimator,
        )
        sub_stage = self.list_of_callables[0](self.list_of_callables[1:], self.ctx)
        yield from sub_stage.run()


class MinimalBandwidthLatencyStage(ZigZagStage):
    """Class that keeps yields only the cost model evaluation that has minimal objective function of all cost model
    evaluations generated by it's substages created by list_of_callables.
    The objective function is defined as:
        `ceil(nb_parallel_nodes * required_dram_bandwidth / total_dram_bandwidth) * latency`
    """

    def __init__(
        self,
        list_of_callables: list[StageCallable],
        *,
        reduce_minimal_keep_others: bool = False,
        **kwargs: Any,
    ) -> None:
        """
        Initialize the compare stage.
        """
        super().__init__(list_of_callables, **kwargs)
        self.ctx = StageContext.from_kwargs(**kwargs)
        self.keep_others = reduce_minimal_keep_others
        accelerator: Core = self.ctx.require_value("accelerator", self.__class__.__name__)
        self.nb_parallel_nodes: int = self.ctx.get("nb_parallel_nodes", 1)
        self.has_dram_level: bool = self.ctx.get("has_dram_level", False)

        self.mem_ops_with_dram: list[MemoryOperand] = []
        self.mem_ops = list(accelerator.memory_hierarchy.operands)
        self.total_dram_bandwidth: int | None = None

        if self.has_dram_level:
            nb_levels_per_op = [len(accelerator.memory_hierarchy.get_memory_levels(op)) for op in self.mem_ops]
            dram_mem_level = max(nb_levels_per_op)  # start at 1
            self.mem_ops_with_dram = [
                op for op, nb_levels in zip(self.mem_ops, nb_levels_per_op, strict=False) if nb_levels == dram_mem_level
            ]
            ports = accelerator.get_top_memory_instance(self.mem_ops_with_dram[0]).ports
            self.total_dram_bandwidth = max((port.bw_max for port in ports), default=0)

    def get_used_dram_bandwidth_for_op(self, cme: CostModelEvaluation, mem_op: MemoryOperand):
        if mem_op not in self.mem_ops_with_dram:
            return 0
        bw_per_direction = 100  # TODO: maybe this is wrong
        total_bw = sum(bw_per_direction.data.values())
        return total_bw

    def objective_function(self, cme: CostModelEvaluation) -> float:
        """
        # TODO this does not cover all cases
        """
        from math import ceil
        latency: int = int(cme.latency_total2)

        if not self.has_dram_level:
            return latency

        assert self.total_dram_bandwidth is not None

        match len(self.mem_ops_with_dram):
            case 1:
                total_used_dram_bw = self.nb_parallel_nodes * self.get_used_dram_bandwidth_for_op(
                    cme, self.mem_ops_with_dram[0]
                )
            case 2:
                # Assume that 1 operand is broadcasted to all cores and only needs 1 simultaneous transfer for all cores
                # We don't know which operand is broadcasted, so just pick one that is not the output
                broadcast_op = next(op for op in self.mem_ops_with_dram if op != Constants.OUTPUT_MEM_OP)
                other_op = next(op for op in self.mem_ops_with_dram if op != broadcast_op)
                bw_for_broadcasting = 1 * self.get_used_dram_bandwidth_for_op(cme, broadcast_op)
                bw_for_blocking = self.nb_parallel_nodes * self.get_used_dram_bandwidth_for_op(cme, other_op)
                total_used_dram_bw = bw_for_blocking + bw_for_broadcasting
            case 3:
                # We don't know broadcast op, just pick one that is not the output
                broadcast_op = next(op for op in self.mem_ops_with_dram if op != Constants.OUTPUT_MEM_OP)
                other_ops = [op for op in self.mem_ops_with_dram if op != broadcast_op]

                bw_for_broadcasting = 1 * self.get_used_dram_bandwidth_for_op(cme, broadcast_op)
                bw_for_blocking = self.nb_parallel_nodes * sum(
                    self.get_used_dram_bandwidth_for_op(cme, mem_op) for mem_op in other_ops
                )
                total_used_dram_bw = bw_for_blocking + bw_for_broadcasting
            case _:
                raise NotImplementedError

        return ceil(total_used_dram_bw / self.total_dram_bandwidth) * latency

    def run(self):
        """! Run the compare stage by comparing a new cost model output with the current best found result."""
        sub_list_of_callables = self.list_of_callables[1:]
        substage: ZigZagStage = self.list_of_callables[0](sub_list_of_callables, **self.ctx.data)

        other_cmes: list[tuple[CostModelEvaluation, Any]] = []
        best_cme: CostModelEvaluation | None = None
        for cme, extra_info in substage.run():
            assert isinstance(cme, CostModelEvaluation)
            if best_cme is None or self.objective_function(cme) < self.objective_function(best_cme):
                best_cme = cme
            if self.keep_others:
                other_cmes.append((cme, extra_info))

        assert best_cme is not None
        yield best_cme, other_cmes
