name: MkDocs CI/CD

on:
  # Trigger only when docs/ changes land on main (e.g., after your ingest workflow commits)
  push:
    branches: [main]
    paths:
      - 'docs/**'
  # Optional manual trigger
  workflow_dispatch:

permissions:
  contents: write  # required by peaceiris/actions-gh-pages to push to gh-pages

concurrency:
  group: mkdocs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs dependencies
        run: |
          cd docs
          pip install -r requirements.txt

      - name: Build MkDocs site (docs_dir: source)
        run: |
          cd docs
          mkdocs build --config-file mkdocs.yml --strict
          # Output is at docs/site by default

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/site
          # Optional knobs:
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # commit_message: "docs: publish site"